### ISSUE TITLE
Ability to customise tag prefix

### ISSUE THREAD

**Issue by mpurins-nc** [dwijnand/sbt-dynver#149]
Hi,

I would like to kindly ask for ability to customise tag prefix. So instead of hard coded `v` I could use anything as prefix.

Currently I want to introduce sbt-dynver to project I have started to work in, but company has long standing convention to tag versions using `v-` (yes that one dash holds me back :( ).
Would it be feasible feature for sbt-dynver?
If PR with such feature will be accepted I can try to do it once I have time.

Thanks

**Comment by dwijnand** [comment]
I don't think I can tell you upfront if I would accept such a feature.  It would depend on what the result of implementing it looked like.  I have vague memories when I added the "v" prefix that I specifically kept it "v" specific because there are a few bits and pieces that need to work together:

* [the pattern to specify to `git describe`](https://github.com/dwijnand/sbt-dynver/blob/4b99be7cb806dda4d9fc0b79c85e6d59d1913dd9/src/main/scala/sbtdynver/DynVerPlugin.scala#L188)
* [the pattern to use when reading that output](https://github.com/dwijnand/sbt-dynver/blob/4b99be7cb806dda4d9fc0b79c85e6d59d1913dd9/src/main/scala/sbtdynver/DynVerPlugin.scala#L140)
* [the `isTag` and `dropV` methods](https://github.com/dwijnand/sbt-dynver/blob/4b99be7cb806dda4d9fc0b79c85e6d59d1913dd9/src/main/scala/sbtdynver/DynVerPlugin.scala#L87-L88)
* [and this little thing...](https://github.com/dwijnand/sbt-dynver/blob/4b99be7cb806dda4d9fc0b79c85e6d59d1913dd9/src/main/scala/sbtdynver/DynVerPlugin.scala#L152-L153)

Have a go, and let me know how it goes.

**Comment by mpurins-nc** [comment]
I never got around to playing with this and no longer actual to me but I believe that PR #158 released with 4.1.0 implements what I wanted. Thanks @sideeffffect!
