### ISSUE TITLE
MetaData and Pre-Release Order Incorrect

### ISSUE THREAD

**Issue by apeschel** [dwijnand/sbt-dynver#93]
DynVer currently produces SemVer-ish, but invalid versions with the pre-release and metadata fields reversed.

As per the [SemVer spec](https://github.com/semver/semver/blob/master/semver.md#backusnaur-form-grammar-for-valid-semver-versions), the order should be

```
<version core> "-" <pre-release> "+" <build>
```

**Comment by dwijnand** [comment]
This is intentional.  SemVer only has pre-release modifiers and has no way to convey post-release versions.  There are a few threads in the SemVer spec repo where I (along with some others) try and request support for this (to no success).

Given `-` is the separator for pre-release, `+` is (IMO) a good separator for post-release, thus `1.0.0+3-1234abcd`.

Contrary to the SemVer spec, the information in `+` segment is _not_ build information and it _is_ relevant to version precendence (`1.0.0+3-1234abcd` is not the same as `1.0.0+2-3452afed`).

Do you think it would be an improvment to mention this in the README, or do you think it's a niche concern?

**Comment by apeschel** [comment]
@dwijnand Probably worth mentioning in the README, since the example seem to imply an attempt at compatibility with SemVer, so the intentional divergence is of worthy note.
